### ISSUE TITLE
expireAt rounding

### ISSUE THREAD

**Issue by Mododo** [broxus/everscale-standalone-client#6]
With locklift 2.4.6 using
* everscale-inpage-provider 0.3.45
* everscale-standalone-client 2.1.5 
```
     Error: Expected integer value: 1672031328.4
      at module.exports.__wbg_new_8d2af00bc1e329ee (node_modules/nekoton-wasm/nekoton_wasm_main.js:1830:17)
      at null.<anonymous> (wasm://wasm/004fc35e:1:900709)
      at null.<anonymous> (wasm://wasm/004fc35e:1:630868)
      at Object.module.exports.packIntoCell (node_modules/nekoton-wasm/nekoton_wasm_main.js:445:14)
      at AccountsStorageContext.packIntoCell (node_modules/everscale-standalone-client/client/AccountsStorage/index.js:56:29)
      at WalletV3Account.prepareMessage (node_modules/everscale-standalone-client/client/AccountsStorage/WalletV3.js:61:37)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at sendMessage (node_modules/everscale-standalone-client/client/index.js:737:31)
      at ContractMethodImpl.send (node_modules/everscale-inpage-provider/dist/contract.js:299:33)
```

the code i hit [looks like](https://github.com/broxus/everscale-standalone-client/blob/master/src/client/index.ts#L831) and occurs in several places
```
timeout *= properties.message.timeoutGrowFactor
```
so timeout changes as 60, 72, 86.39999999999999, 103.67999999999999, 124.41599999999998, 60

**Comment by Rexagon** [comment]
Should be fixed in `2.1.6`
